export {default as Artical} from "./artical/Artical"
export {default as Brand} from "./brand/Brand"
export {default as CTA} from "./CTA/CTA"
export {default as Navbar} from "./navbar/Navbar"
export {default as Feature} from "./feature/Feature"
